[build]
command = "npm run build"
publish = "build"

[build.environment]
  NODE_VERSION = "14.17.6"
  NPM_VERSION = "7.24.1"

# [[headers]]
#   for = "/*"
#   [headers.values]
#     Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
#     Content-Security-Policy = "default-src data: 'unsafe-inline' 'unsafe-eval' https:; script-src data: 'unsafe-inline' 'unsafe-eval' https: blob:; style-src data: 'unsafe-inline' https:; img-src data: https: blob:; font-src data: https:; connect-src https: wss: blob:; media-src https: blob:; object-src https:; child-src https: data: blob:; form-action https:; block-all-mixed-content"
#     X-Frame-Options = "DENY"
#     X-Content-Type-Options = "nosniff"
#     Referrer-Policy = "no-referrer"
#     Feature-Policy = "microphone 'none'; geolocation 'none'"
