import { describe, expect, it } from 'vitest';
import { loadSeed } from '$lib/data/seed';
import { isLive, isValid, toDraft } from '$lib/domain/note';

/**
 * The seed file is generated by `pnpm generateData`, which deliberately keeps
 * its own shape. These tests guard the mapping between the two, so a change to
 * the generator fails here rather than at a user's first page load.
 */
describe('loadSeed', () => {
  const seeded = loadSeed();

  it('produces notes', () => {
    expect(seeded.length).toBeGreaterThan(0);
  });

  it('gives every note a unique id', () => {
    expect(new Set(seeded.map(note => note.id)).size).toBe(seeded.length);
  });

  it('produces notes that would pass validation', () => {
    for (const note of seeded) expect(isValid(toDraft(note))).toBe(true);
  });

  it('produces live, unsynced notes', () => {
    for (const note of seeded) {
      expect(isLive(note)).toBe(true);
      expect(note.deletedAt).toBeNull();
      expect(note.syncedAt).toBeNull();
    }
  });

  it('uses parseable ISO timestamps', () => {
    for (const note of seeded) {
      expect(Number.isNaN(Date.parse(note.createdAt))).toBe(false);
      expect(Number.isNaN(Date.parse(note.updatedAt))).toBe(false);
    }
  });

  it('joins the generator’s paragraph array into markdown-ready body text', () => {
    const multiParagraph = seeded.find(note => note.body.includes('\n\n'));

    expect(multiParagraph, 'no seed note has more than one paragraph').toBeDefined();
    expect(multiParagraph!.body).not.toContain('\n\n\n');
  });

  it('returns a fresh array each call, so callers cannot corrupt the seed', () => {
    const first = loadSeed();
    first[0].title = 'Mutated';

    expect(loadSeed()[0].title).not.toBe('Mutated');
  });
});
